#ifndef ERRORS_H
#define ERRORS_H

// Exit codes
#define EXIT_NO_ARGUMENTS 1
#define EXIT_EMPTY_ARG 2
#define EXIT_NON_EXISTENT_COMMAND 3
#define EXIT_TOO_MANY_ARGS 4
#define EXIT_INVALID_ARG 20
#define EXIT_FILE_CANNOT_BE_READ 9
#define EXIT_OUTPUT_FILE_ERROR 11
#define EXIT_NO_COMMAND 6
#define EXIT_MISSING_INPUT_FILE 88
#define EXIT_INVALID_FILE_TYPE 89
#define EXIT_INVALID_PARAMETER 90
#define EXIT_SAME_FILE 91

typedef int make_compiler_happy;

#endif
